name: test

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install xcodegen
        run: brew install xcodegen
      - name: Unit tests
        run: ./Scripts/test.sh
      - name: UI tests
        run: ./Scripts/test.sh --ui
